spring:
  application:
    name: chinapopin-evaluate-web
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    port: 8088
datasource:
  enableSlave:
  type: com.alibaba.druid.pool.DruidDataSource
  master:
    #url: jdbc:mysql://100.98.100.253:3306/rkw_test?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    #username: rkwtest
    #password: tEst@2013
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@10.64.39.117:1521:rktestdb
    username: rktest
    password: a
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 20
    initial-size: 2
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    poolPreparedStatements: true
logging:
  config: classpath:log4j2.xml
deptId: 510000000000
#evaluateHttpUrl: http://10.64.54.237:8090/sjba
evaluateHttpUrl: http://10.64.39.122:8080
redis:
  # Redis服务器地址
  host: localhost
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password:
  # 连接超时时间（毫秒）
  timeout: 12000
  # Redis数据库索引（默认为0）
  database: 0
  pool:
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 30
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: 10000
    # 连接池中的最大空闲连接
    max-idle: 15
    # 连接池中的最小空闲连接
    min-idle: 5